language: swift
osx_image: xcode10.1
script:
    - xcodebuild clean test -project DartMania.xcodeproj -scheme DartMania -destination "platform=iOS Simulator,name=iPhone 7,OS=12.1" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet